
CREATE DATABASE IF NOT EXISTS vacay_db;
USE vacay_db;


CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    role ENUM('user', 'admin') DEFAULT 'user'
) ENGINE=InnoDB 
  DEFAULT CHARSET= utf8mb4
  COLLATE=utf8mb4_unicode_ci; 


CREATE TABLE IF NOT EXISTS Countries (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )ENGINE=InnoDB   
    DEFAULT CHARSET= utf8mb4
    COLLATE=utf8mb4_unicode_ci;


 CREATE TABLE IF NOT EXISTS States (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    country_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (country_id) REFERENCES Countries(id) ON DELETE CASCADE
  )ENGINE=InnoDB 
  DEFAULT CHARSET= utf8mb4
  COLLATE=utf8mb4_unicode_ci;