Use vaycay_db;

CREATE TABLE IF NOT EXISTS departures (
    id INT AUTO_INCREMENT PRIMARY KEY,
    start_date TIMESTAMP NOT NULL ,
    end_date TIMESTAMP NOT NULL,
    total_seats INT NOT NULL,
    available_seats INT,
    trip_id INT,
    destintaion_id INT,
    FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS itenary (
id INT AUTO_INCREMENT PRIMARY KEY,
departure_id INT NOT NULL,
itenary_days INT NOT NULL,
description VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
FOREIGN KEY (departure_id) REFERENCES departures(id) ON DELETE CASCADE

)

CREATE TABLE IF NOT EXISTS travellers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    departure_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (departure_id) REFERENCES departures(id) ON DELETE CASCADE
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE

)

